# Generated by Django 3.0 on 2022-02-15 10:48

from django.db import migrations, models


def update_contentypes(apps, schema_editor):
    """
    Updates content types.
    We want to have the same content type id, when the model is moved.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias
    # Move the profile model to profiles
    qs = ContentType.objects.using(db_alias).filter(
        app_label='oc_lettings_site', model='Profile')
    qs.update(app_label='profiles')


def update_contentypes_reverse(apps, schema_editor):
    """
    Reverts changes in content types.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    db_alias = schema_editor.connection.alias
    # Move the TrackingAlert model to tracking
    qs = ContentType.objects.using(db_alias).filter(
        app_label='oc_lettings_site', model='Profile')
    qs.update(app_label='profiles')


class Migration(migrations.Migration):
    dependencies = [

    ]

    state_operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(
                    on_delete=models.deletion.CASCADE, to='auth.User')),
                ('favorite_city', models.CharField(max_length=64, blank=True))

            ],
        ),
            ]

    database_operations = [
        migrations.RunPython(update_contentypes, update_contentypes_reverse),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=database_operations
        ),
    ]
