# Generated by Django 3.0 on 2022-02-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='lettings_address',
        ),
    ]
