# Generated by Django 3.0 on 2022-02-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='lettings_address',
        ),
        migrations.AlterModelTable(
            name='letting',
            table='lettings_letting',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles_profile',
        ),
    ]
