# Generated by Django 3.0 on 2022-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220215_1109'),
        ('lettings', '0001_initial'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='Letting',
            name='address',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE,
                                    to='lettings.Address'),
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]