# Generated by Django 3.0 on 2022-02-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20220215_1130'),
        ('oc_lettings_site', '0004_auto_20220215_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letting',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lettings.Address'),
        ),
    ]
