# Generated by Django 3.0 on 2022-02-15 10:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0005_auto_20220215_1130'),
    ]

    state_operations = [
        migrations.DeleteModel('Letting'),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]