# Generated by Django 3.0 on 2022-02-15 10:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0006_auto_20220215_1134'),
    ]

    state_operations = [
        migrations.DeleteModel('Profile'),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]